# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcpIpList < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mark-adams/gcp-ip-list/releases/download/v0.0.1/gcp-ip-list_Darwin_x86_64.tar.gz"
      sha256 "a873854b758b6f334967a863ed5e4fed703a3374240ab56dee16345af052746d"

      def install
        bin.install "gcp-ip-list"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mark-adams/gcp-ip-list/releases/download/v0.0.1/gcp-ip-list_Darwin_arm64.tar.gz"
      sha256 "01ac7f7f7a7b53fd8550627da3b7ecd8500fd62c134dc1126233e33e2ab3893f"

      def install
        bin.install "gcp-ip-list"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mark-adams/gcp-ip-list/releases/download/v0.0.1/gcp-ip-list_Linux_x86_64.tar.gz"
        sha256 "8e6bd288c022dd88bb61ca6dc67932c19e594801997d8f23cf4b3246b3121146"

        def install
          bin.install "gcp-ip-list"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mark-adams/gcp-ip-list/releases/download/v0.0.1/gcp-ip-list_Linux_arm64.tar.gz"
        sha256 "13a10d8b960b5f0d8302a1f0de1f1e40007255939f62a0a451efcc530206e96a"

        def install
          bin.install "gcp-ip-list"
        end
      end
    end
  end
end
